---
title: "My first blog post"
date: 2018-09-18
---

title: Karen's Super Cool Portfolio Site/ Blog
author: Karen
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Karen's portfolio site and blog. Please check in often for updates on projects and computer science/ programming tidbits.

# social links
twitter_username: your-twitter-handle
github_username:  @kberba

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
